name: Activity Tracker CI

on:
  push:
    branches:
      - master
      - "develop/*"
      - "features/*"
      - Test

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
              
      - name: Run build script
        run: |
          chmod +x ./activity.sh
          ./activity.sh build
        shell: bash